### ISSUE TITLE
Update Android project for Flutter 3.7+

### ISSUE THREAD

**Issue by matiasilveiro** [enzoftware/flutter_accessibility_expense_tracker#1]
Hey! I had some issues trying to run the Android project in Flutter 3.7.10.
To run this project in newer versions of Flutter you have to make these small changes:

- Replace AndroidManifest.xml line 9 with `android:name="${applicationName}"`
- Add in AndroidManifest.xml `android:exported="true"` property at `activity` level tag (line 15 for example)
- Replace gradle-wrapper.properties line 6 (Gradle distribution) with this URL: `https\://services.gradle.org/distributions/gradle-7.5-all.zip`
- Replace `kotlin_version` with `1.7.10` in build.gradle (project)
- Replace `com.android.tools.build:gradle` version with `7.2.0` in build.gradle (project)
- Update Android SDK versions in build.gradle (module) to: `compileSdkVersion 33`, `minSdkVersion 26` and `targetSdkVersion 33`

I'll try to create a PR later!

**Comment by enzoftware** [comment]
I'll appreciate it a lot if you can make the PR! Thanks!

**Comment by matiasilveiro** [comment]
Hey Enzo! I created two PRs, to push the update into both starter and final branches. PR #2 and PR #3.

Your article is amazing! I loved it and it was very hepful for my projects.

**Comment by enzoftware** [comment]
Thanks for your work!
